'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ErxCartClearEvent, type ErxCartCustomEvent, type ErxCartItem, type ErxCartItemChangeEvent, type ErxCartItemRemoveEvent, type ErxCartSummary, type ErxCategorySelectEvent, type ErxCategoryTabsCustomEvent, type ErxCellEditEvent, type ErxCellEditStartEvent, type ErxDataGridCustomEvent, type ErxFilterEvent, type ErxOrder, type ErxOrderTicketActionEvent, type ErxOrderTicketCustomEvent, type ErxPageChangeEvent, type ErxPaymentCompleteEvent, type ErxPaymentCustomEvent, type ErxPaymentSelectEvent, type ErxPinPadChangeEvent, type ErxPinPadCustomEvent, type ErxPinPadSubmitEvent, type ErxProductCardAddEvent, type ErxProductCardCustomEvent, type ErxProductCardSelectEvent, type ErxRowClickEvent, type ErxRowSelectEvent, type ErxSortEvent, type ErxSplitPaneCollapseEvent, type ErxSplitPaneCustomEvent, type ErxSplitPaneResizeEvent, type ErxVariantSelectEvent, type ErxVariantSelection, type ErxVariantSelectorCustomEvent } from "@erplora/erx";
import { ErxCart as ErxCartElement, defineCustomElement as defineErxCart } from "@erplora/erx/dist/components/erx-cart.js";
import { ErxCategoryTabs as ErxCategoryTabsElement, defineCustomElement as defineErxCategoryTabs } from "@erplora/erx/dist/components/erx-category-tabs.js";
import { ErxDataGrid as ErxDataGridElement, defineCustomElement as defineErxDataGrid } from "@erplora/erx/dist/components/erx-data-grid.js";
import { ErxOrderTicket as ErxOrderTicketElement, defineCustomElement as defineErxOrderTicket } from "@erplora/erx/dist/components/erx-order-ticket.js";
import { ErxPayment as ErxPaymentElement, defineCustomElement as defineErxPayment } from "@erplora/erx/dist/components/erx-payment.js";
import { ErxPinPad as ErxPinPadElement, defineCustomElement as defineErxPinPad } from "@erplora/erx/dist/components/erx-pin-pad.js";
import { ErxProductCard as ErxProductCardElement, defineCustomElement as defineErxProductCard } from "@erplora/erx/dist/components/erx-product-card.js";
import { ErxReceipt as ErxReceiptElement, defineCustomElement as defineErxReceipt } from "@erplora/erx/dist/components/erx-receipt.js";
import { ErxSplitPane as ErxSplitPaneElement, defineCustomElement as defineErxSplitPane } from "@erplora/erx/dist/components/erx-split-pane.js";
import { ErxVariantSelector as ErxVariantSelectorElement, defineCustomElement as defineErxVariantSelector } from "@erplora/erx/dist/components/erx-variant-selector.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type ErxCartEvents = {
    onErxItemChange: EventName<ErxCartCustomEvent<ErxCartItemChangeEvent>>,
    onErxItemRemove: EventName<ErxCartCustomEvent<ErxCartItemRemoveEvent>>,
    onErxClear: EventName<ErxCartCustomEvent<ErxCartClearEvent>>,
    onErxCheckout: EventName<ErxCartCustomEvent<{ summary: ErxCartSummary; items: ErxCartItem[] }>>
};

export const ErxCart: StencilReactComponent<ErxCartElement, ErxCartEvents> = /*@__PURE__*/ createComponent<ErxCartElement, ErxCartEvents>({
    tagName: 'erx-cart',
    elementClass: ErxCartElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxItemChange: 'erxItemChange',
        onErxItemRemove: 'erxItemRemove',
        onErxClear: 'erxClear',
        onErxCheckout: 'erxCheckout'
    } as ErxCartEvents,
    defineCustomElement: defineErxCart
});

type ErxCategoryTabsEvents = { onErxSelect: EventName<ErxCategoryTabsCustomEvent<ErxCategorySelectEvent>> };

export const ErxCategoryTabs: StencilReactComponent<ErxCategoryTabsElement, ErxCategoryTabsEvents> = /*@__PURE__*/ createComponent<ErxCategoryTabsElement, ErxCategoryTabsEvents>({
    tagName: 'erx-category-tabs',
    elementClass: ErxCategoryTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onErxSelect: 'erxSelect' } as ErxCategoryTabsEvents,
    defineCustomElement: defineErxCategoryTabs
});

type ErxDataGridEvents = {
    onErxSort: EventName<ErxDataGridCustomEvent<ErxSortEvent>>,
    onErxFilter: EventName<ErxDataGridCustomEvent<ErxFilterEvent>>,
    onErxRowSelect: EventName<ErxDataGridCustomEvent<ErxRowSelectEvent>>,
    onErxRowClick: EventName<ErxDataGridCustomEvent<ErxRowClickEvent>>,
    onErxRowDoubleClick: EventName<ErxDataGridCustomEvent<ErxRowClickEvent>>,
    onErxCellEdit: EventName<ErxDataGridCustomEvent<ErxCellEditEvent>>,
    onErxCellEditStart: EventName<ErxDataGridCustomEvent<ErxCellEditStartEvent>>,
    onErxCellEditCancel: EventName<ErxDataGridCustomEvent<ErxCellEditStartEvent>>,
    onErxPageChange: EventName<ErxDataGridCustomEvent<ErxPageChangeEvent>>
};

export const ErxDataGrid: StencilReactComponent<ErxDataGridElement, ErxDataGridEvents> = /*@__PURE__*/ createComponent<ErxDataGridElement, ErxDataGridEvents>({
    tagName: 'erx-data-grid',
    elementClass: ErxDataGridElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxSort: 'erxSort',
        onErxFilter: 'erxFilter',
        onErxRowSelect: 'erxRowSelect',
        onErxRowClick: 'erxRowClick',
        onErxRowDoubleClick: 'erxRowDoubleClick',
        onErxCellEdit: 'erxCellEdit',
        onErxCellEditStart: 'erxCellEditStart',
        onErxCellEditCancel: 'erxCellEditCancel',
        onErxPageChange: 'erxPageChange'
    } as ErxDataGridEvents,
    defineCustomElement: defineErxDataGrid
});

type ErxOrderTicketEvents = {
    onErxAction: EventName<ErxOrderTicketCustomEvent<ErxOrderTicketActionEvent>>,
    onErxSelect: EventName<ErxOrderTicketCustomEvent<{ order: ErxOrder }>>
};

export const ErxOrderTicket: StencilReactComponent<ErxOrderTicketElement, ErxOrderTicketEvents> = /*@__PURE__*/ createComponent<ErxOrderTicketElement, ErxOrderTicketEvents>({
    tagName: 'erx-order-ticket',
    elementClass: ErxOrderTicketElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxAction: 'erxAction',
        onErxSelect: 'erxSelect'
    } as ErxOrderTicketEvents,
    defineCustomElement: defineErxOrderTicket
});

type ErxPaymentEvents = {
    onErxSelect: EventName<ErxPaymentCustomEvent<ErxPaymentSelectEvent>>,
    onErxComplete: EventName<ErxPaymentCustomEvent<ErxPaymentCompleteEvent>>
};

export const ErxPayment: StencilReactComponent<ErxPaymentElement, ErxPaymentEvents> = /*@__PURE__*/ createComponent<ErxPaymentElement, ErxPaymentEvents>({
    tagName: 'erx-payment',
    elementClass: ErxPaymentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxSelect: 'erxSelect',
        onErxComplete: 'erxComplete'
    } as ErxPaymentEvents,
    defineCustomElement: defineErxPayment
});

type ErxPinPadEvents = {
    onErxChange: EventName<ErxPinPadCustomEvent<ErxPinPadChangeEvent>>,
    onErxSubmit: EventName<ErxPinPadCustomEvent<ErxPinPadSubmitEvent>>,
    onErxClear: EventName<CustomEvent<void>>,
    onErxKeyPress: EventName<CustomEvent<{ key: string }>>
};

export const ErxPinPad: StencilReactComponent<ErxPinPadElement, ErxPinPadEvents> = /*@__PURE__*/ createComponent<ErxPinPadElement, ErxPinPadEvents>({
    tagName: 'erx-pin-pad',
    elementClass: ErxPinPadElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxChange: 'erxChange',
        onErxSubmit: 'erxSubmit',
        onErxClear: 'erxClear',
        onErxKeyPress: 'erxKeyPress'
    } as ErxPinPadEvents,
    defineCustomElement: defineErxPinPad
});

type ErxProductCardEvents = {
    onErxSelect: EventName<ErxProductCardCustomEvent<ErxProductCardSelectEvent>>,
    onErxAdd: EventName<ErxProductCardCustomEvent<ErxProductCardAddEvent>>,
    onErxQuantityChange: EventName<CustomEvent<{ quantity: number }>>
};

export const ErxProductCard: StencilReactComponent<ErxProductCardElement, ErxProductCardEvents> = /*@__PURE__*/ createComponent<ErxProductCardElement, ErxProductCardEvents>({
    tagName: 'erx-product-card',
    elementClass: ErxProductCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxSelect: 'erxSelect',
        onErxAdd: 'erxAdd',
        onErxQuantityChange: 'erxQuantityChange'
    } as ErxProductCardEvents,
    defineCustomElement: defineErxProductCard
});

type ErxReceiptEvents = NonNullable<unknown>;

export const ErxReceipt: StencilReactComponent<ErxReceiptElement, ErxReceiptEvents> = /*@__PURE__*/ createComponent<ErxReceiptElement, ErxReceiptEvents>({
    tagName: 'erx-receipt',
    elementClass: ErxReceiptElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as ErxReceiptEvents,
    defineCustomElement: defineErxReceipt
});

type ErxSplitPaneEvents = {
    onErxResize: EventName<ErxSplitPaneCustomEvent<ErxSplitPaneResizeEvent>>,
    onErxResizeStart: EventName<CustomEvent<void>>,
    onErxResizeEnd: EventName<ErxSplitPaneCustomEvent<ErxSplitPaneResizeEvent>>,
    onErxCollapse: EventName<ErxSplitPaneCustomEvent<ErxSplitPaneCollapseEvent>>
};

export const ErxSplitPane: StencilReactComponent<ErxSplitPaneElement, ErxSplitPaneEvents> = /*@__PURE__*/ createComponent<ErxSplitPaneElement, ErxSplitPaneEvents>({
    tagName: 'erx-split-pane',
    elementClass: ErxSplitPaneElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxResize: 'erxResize',
        onErxResizeStart: 'erxResizeStart',
        onErxResizeEnd: 'erxResizeEnd',
        onErxCollapse: 'erxCollapse'
    } as ErxSplitPaneEvents,
    defineCustomElement: defineErxSplitPane
});

type ErxVariantSelectorEvents = {
    onErxSelect: EventName<ErxVariantSelectorCustomEvent<ErxVariantSelectEvent>>,
    onErxComplete: EventName<ErxVariantSelectorCustomEvent<{ selection: ErxVariantSelection }>>
};

export const ErxVariantSelector: StencilReactComponent<ErxVariantSelectorElement, ErxVariantSelectorEvents> = /*@__PURE__*/ createComponent<ErxVariantSelectorElement, ErxVariantSelectorEvents>({
    tagName: 'erx-variant-selector',
    elementClass: ErxVariantSelectorElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onErxSelect: 'erxSelect',
        onErxComplete: 'erxComplete'
    } as ErxVariantSelectorEvents,
    defineCustomElement: defineErxVariantSelector
});
