/**
 * ERX React Bindings
 * Auto-generated by @stencil/react-output-target
 */

// This file will be populated by Stencil during build
// For now, export a placeholder to ensure the package structure is correct

export * from './components';
